--- #YAML:1.0
name:               Carp-Always
version:            0.10
abstract:           Warns and dies noisily with stack backtraces
author:
    - Adriano R. Ferreira <ferreira@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    Test::More:  0
resources:
    repository:  http://github.com/aferreira/cpan-Carp-Always
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Test::Base:           0
    Test::Pod:            0
    Test::Pod::Coverage:  0
